version: '3'
services:
  jobmanager:
    image: pyflink:1.14.5
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager   
    volumes:
      - ./mnt/opt/flink:/tmp/opt/flink  
      - ./mnt/flink_files:/opt/flink/flink_files 

  taskmanager:
    image: pyflink:1.14.5
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 
    volumes: 
      - ./mnt/flink_files:/opt/flink/flink_files 

  sql-client:
    image: pyflink:1.14.5
    container_name: sqlclient
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager   
    volumes: 
      - ./mnt/flink_files:/opt/flink/flink_files 
    
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    ports:
      - "8080:8080"
    depends_on:
      - jobmanager
    environment:
      - FLINK_HOME=/opt/flink
    volumes: 
      - ./mnt/opt/flink:/opt/flink
      - ./mnt/flink_files:/tmp/flink_files 
      - ./mnt/zeppelin/notebook:/zeppelin/notebook
      - ./mnt/zeppelin/logs:/zeppelin/logs
      - ./mnt/zeppelin/conf:/zeppelin/conf
      # - ./mnt/zeppelin/notebook:/opt/zeppelin/notebook
      # - ./mnt/zeppelin/logs:/opt/zeppelin/logs
      # - ./mnt/zeppelin/conf:/opt/zeppelin/conf