version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - ./mnt/zookeeper/data:/var/lib/zookeeper/data
      - ./mnt/zookeeper/log:/var/lib/zookeeper/log
    networks:
      - kafkaflink

  broker-1:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker-1
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker-1:9092,PLAINTEXT://localhost:19092
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_LOG_DIRS: /kafka
    volumes:
      - ./mnt/broker1:/kafka
    networks:
      - kafkaflink

  broker-2:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker-2
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker-2:9092,PLAINTEXT://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_LOG_DIRS: /kafka
    volumes:
      - ./mnt/broker2:/kafka
    networks:
      - kafkaflink

  broker-3:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker-3
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker-3:9092,PLAINTEXT://localhost:39092
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_LOG_DIRS: /kafka
    volumes:
      - ./mnt/broker3:/kafka
    networks:
      - kafkaflink

  pyspark:
    image: jupyter/pyspark-notebook:spark-3.3.0
    container_name: pyspark
    container_name: pyspark
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - "./mnt/pyspark/:/home/jovyan/"
    networks:
      - kafkaflink

  grafana:
    image: grafana/grafana:9.0.6
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./mnt/grafana:/var/lib/grafana
    networks:
      - kafkaflink

  postgres:
    image: postgres:14.4
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: MyPassw0rd!
      POSTGRES_DB: visual
    volumes:
      - ./mnt/postgres:/var/lib/postgresql/data/
    networks:
      - kafkaflink


networks:
  kafkaflink:
    name: kafkaflink
    